matrix:
  include:
    - os: linux
      #dist: trusty
      env: PLATFORM=linux CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'cmake', 'gcc-4.9', 'g++-4.9' ]
    - os: osx
      env: PLATFORM=osx
      compiler: clang
      #osx_image: xcode7

before_install:
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp embree.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install embree tbb cmake ; fi

script:
  - cmake . -Bbuild
  - cmake --build build
